/* tslint:disable */
/* eslint-disable */
/**
 * API de Ventas
 * API para gestión de ventas
 *
 * The version of the OpenAPI document: 1.0
 * Contact: soporte@miempresa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";

export const BASE_PATH = "http://localhostestenoes:8080".replace(/\/+$/, "");

export const COLLECTION_FORMATS = {
  csv: ",",
  ssv: " ",
  tsv: "\t",
  pipes: "|",
};

export interface RequestArgs {
  url: string;
  options: RawAxiosRequestConfig;
}

export class BaseAPI {
  protected configuration: Configuration | undefined;
  protected basePath: string;
  protected axios: AxiosInstance;

  constructor(
    configuration?: Configuration,
    basePath?: string,
    axios?: AxiosInstance
  ) {
    this.basePath = basePath ?? BASE_PATH;
    this.axios = axios ?? globalAxios;

    if (configuration) {
      this.configuration = configuration;
      this.basePath = configuration.basePath ?? basePath ?? BASE_PATH;
      console.log("BaseAPI basePath:", this.basePath);
      console.log("BaseAPI basePath:", configuration.basePath);
      console.log("BaseAPI axios:", this.configuration);
    }
  }
}

export class RequiredError extends Error {
  public field: string;
  constructor(field: string, msg?: string) {
    super(msg);
    this.field = field;
    this.name = "RequiredError";
  }
}

interface ServerMap {
  [key: string]: {
    url: string;
    description: string;
  }[];
}

export const operationServerMap: ServerMap = {};
